# Generated by Django 5.1.5 on 2025-03-19 14:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditDetail',
            fields=[
                ('credit_details_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('credit_status', models.IntegerField(choices=[(1, 'Complete'), (0, 'Incomplete')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('curriculum_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('curriculum_name', models.CharField(max_length=200)),
                ('total_credit', models.IntegerField()),
                ('curriculum_year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('otp_verification_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('otp', models.CharField(max_length=6)),
                ('reference_otp', models.CharField(editable=False, max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('student_code', models.CharField(blank=True, max_length=10, null=True)),
                ('role', models.CharField(choices=[('student', 'Student'), ('inspector', 'Inspector')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=200)),
                ('category_min_credit', models.IntegerField()),
                ('curriculum_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.curriculum')),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('subcategory_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('subcategory_name', models.CharField(max_length=200)),
                ('subcateory_min_credit', models.IntegerField()),
                ('category_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('credit', models.IntegerField()),
                ('course_name_th', models.CharField(max_length=200)),
                ('course_name_en', models.CharField(max_length=200)),
                ('subcategory_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='SubcategoryDetails',
            fields=[
                ('subcategory_detail_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('acquired_credit', models.IntegerField()),
                ('credit_details_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.creditdetail')),
                ('subcateory_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('form_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('form_status', models.CharField(choices=[('ready to calc', 'Ready To Calc'), ('draft', 'Draft'), ('pending', 'Pending'), ('verified', 'Verified')], default='draft', max_length=20)),
                ('form_type', models.CharField(choices=[('credit check', 'Credit Check'), ('graduation check', 'Graduation Check')], default='graduation check', max_length=20)),
                ('user_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('enrollment_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('semester', models.IntegerField(choices=[(0, 'Summer'), (1, 'First'), (2, 'Second')])),
                ('year', models.IntegerField()),
                ('grade', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('course_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course')),
                ('user_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user')),
            ],
        ),
        migrations.CreateModel(
            name='VerificationResult',
            fields=[
                ('verification_result_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('result_status', models.IntegerField(choices=[(1, 'Pass'), (0, 'Not Pass')], default=0)),
                ('activity_status', models.IntegerField(choices=[(1, 'Pass'), (0, 'Not Pass')], default=0)),
                ('form_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.form')),
            ],
        ),
        migrations.AddField(
            model_name='creditdetail',
            name='verification_result_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.verificationresult'),
        ),
    ]
