name: Backend Action
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
    pull_request: 
        branches: 
            - develop
jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            max-parallel: 4

        steps:
            - uses: actions/checkout@v4

            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v5
              with:
                python-version: ${{ matrix.python-version }}

            - name: Run docker compose
              uses: hoverkraft-tech/compose-action@v2.0.1
              with:
                compose-file: "./Docker-compose.yml"

            - name: Copy environment
              run: cp .env.example ./backend/.env

            - name: Install Dependencies
              working-directory: ./backend
              run: |
                python -m pip install --upgrade pip
                pip install -r requirement.txt

            - name: Run Tests
              working-directory: ./backend
              run: |
                pytest